# Generated by Django 6.0.4 on 2026-04-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kingdom', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('MAGE', 'Mago'), ('WARRIOR', 'Guerrero'), ('ROGUE', 'Picaro'), ('CLERIC', 'Clérigo')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('MISSION', 'En Misión'), ('DEAD', 'Muerto en combate')], default='ACTIVE', max_length=20)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventurers', to='api.guild')),
            ],
        ),
    ]
