# Generated by Django 6.0.4 on 2026-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MAESTRO', 'Maestro del Gremio (Admin)'), ('GUERRERO', 'Guerrero (Ventas)'), ('MAGO', 'Mago (Marketing)'), ('PICARO', 'Pícaro (Operaciones)')], default='GUERRERO', max_length=20),
        ),
    ]
