services:
  # 🗄️ LA BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: rpg_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 🐍 EL MOTOR (DJANGO)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile-python.dev
    container_name: rpg_django
    # El comando que mantiene vivo el servidor de Django para que escuche peticiones
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  # ⚛️ EL FRONTEND (REACT)
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile-vite.dev
  #   container_name: rpg_react
  #   volumes:
  #     # Sincroniza nuestra carpeta local con la virtual
  #     - ./frontend:/app
  #     # Protege los módulos de Node para que no choquen con tu compu
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data: