# Usamos una imagen ligera de Python 3.12
FROM python:3.12-slim

# Evita que Python guarde archivos .pyc en disco (ideal para Docker)
ENV PYTHONDONTWRITEBYTECODE 1

# Evita que Python retrase los prints en la consola
ENV PYTHONUNBUFFERED 1

# Creamos la carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el inventario e instalamos las dependencias
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto del código
COPY . /app/
