# Generated by Django 6.0.4 on 2026-04-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fundacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aventurero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clase_rpg', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Misión', 'En Misión'), ('Enfermería', 'Enfermería'), ('Muerto', 'Muerto')], default='Disponible', max_length=20)),
                ('gremio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aventureros', to='gremio.gremio')),
            ],
        ),
    ]
