# Generated by Django 6.0.4 on 2026-04-27 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('potencial_reward', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('TABERNA', 'Taberna (Nuevo)'), ('EXPLORACION', 'Exploracion (En Proceso)'), ('COMBATE', 'Combate (Negociacion)'), ('TESORO', 'Tesoro (Cerrado Ganado)'), ('CEMENTERIOCementerio (Cerrado Perdido)', 'Cementerio')], default='TABERNA', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
